export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const POST_ACTIVITY = "POST_ACTIVITY"
export const GET_NAME_COUNTRY = "GET_NAME_COUNTRY";
export const GET_DETAIL = "GET_DETAIL";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const ORDER_BY = "ORDER_BY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY"

